print("Name: Atunu Paul")
print("City: Perth")
print("Course: Master of Information Technology")
print()
print("The units I'm currently enrolled at Murdoch University are as follows:")
print("ICT521: IT Professional Practice")
print("ICT581: Information Systems Principles and Practice")
print("ICT582: Python Programming Principles and Practice")
print("ICT583: Data Science Applications")